-- Rebuild Social dimension to strict 10-level pass/fail progression.

create table if not exists public.social_levels (
  id smallint primary key check (id between 1 and 10),
  title text not null,
  description text not null,
  phase text not null check (phase in ('Survival', 'Presence', 'Influence', 'Leverage')),
  score smallint not null default 10 check (score = 10),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.social_requirements (
  id bigint generated by default as identity primary key,
  level_id smallint not null references public.social_levels(id) on delete cascade,
  requirement_text text not null,
  requirement_type text not null check (requirement_type in ('metric', 'manual', 'evidence')),
  required_value text,
  created_at timestamptz not null default now()
);

create table if not exists public.social_progress (
  user_id text not null,
  level_id smallint not null references public.social_levels(id) on delete cascade,
  is_completed boolean not null default false,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, level_id)
);

create table if not exists public.social_evidence (
  id bigint generated by default as identity primary key,
  user_id text not null,
  level_id smallint not null references public.social_levels(id) on delete cascade,
  type text not null check (type in ('chat', 'meetup', 'connection', 'other')),
  note text,
  image_url text,
  created_at timestamptz not null default now()
);

create index if not exists social_requirements_level_idx on public.social_requirements(level_id, id);
create index if not exists social_progress_user_idx on public.social_progress(user_id, level_id);
create index if not exists social_evidence_user_level_idx on public.social_evidence(user_id, level_id, created_at desc);

create trigger set_social_levels_updated_at
before update on public.social_levels
for each row execute function public.set_updated_at_timestamp();

create trigger set_social_progress_updated_at
before update on public.social_progress
for each row execute function public.set_updated_at_timestamp();

-- Remove old Social scoring inputs from generic weighted-metric architecture.
delete from public.smv_metrics
where dimension_id in (select id from public.smv_dimensions where key = 'social');

delete from public.smv_level_definitions
where dimension_id in (select id from public.smv_dimensions where key = 'social');

insert into public.social_levels (id, title, description, phase, score)
values
  (1, 'เปิดวงสนทนา', 'เริ่มต้นคุยกับคนใหม่อย่างเป็นธรรมชาติ', 'Survival', 10),
  (2, 'สร้างความคุ้นเคย', 'มีการ follow-up ภายใน 48 ชั่วโมง', 'Survival', 10),
  (3, 'นัดเจอครั้งแรก', 'เปลี่ยนจากแชทเป็นการเจอจริงอย่างน้อย 1 ครั้ง', 'Survival', 10),
  (4, 'มีตัวตนในวง', 'มีบทบาทเชิงบวกในกลุ่ม/คอมมูนิตี้', 'Presence', 10),
  (5, 'ความน่าเชื่อถือ', 'คนในวงเริ่มนึกถึงคุณเมื่อมีโอกาสหรือปัญหา', 'Presence', 10),
  (6, 'เชื่อมคนกับคน', 'แนะนำคนที่เหมาะสมให้กันและเกิดผลจริง', 'Influence', 10),
  (7, 'สร้างโอกาสร่วม', 'ร่วมโปรเจกต์ กิจกรรม หรือดีลร่วมกับเครือข่าย', 'Influence', 10),
  (8, 'มีอิทธิพลเชิงบวก', 'สามารถขับเคลื่อนบทสนทนา/การตัดสินใจในวง', 'Influence', 10),
  (9, 'ขยายแรงส่ง', 'เครือข่ายของคุณเริ่มชวนคนใหม่เข้ามาโดยไม่ต้องร้องขอ', 'Leverage', 10),
  (10, 'Mission Network Elite', 'เครือข่ายแข็งแรง สร้างผลลัพธ์ต่อเนื่อง และยั่งยืน', 'Leverage', 10)
on conflict (id) do update
set
  title = excluded.title,
  description = excluded.description,
  phase = excluded.phase,
  score = excluded.score,
  updated_at = now();

with requirement_seed as (
  select * from (values
    (1, 'เริ่มแชทใหม่อย่างน้อย 3 คนในสัปดาห์นี้', 'metric', '3'),
    (2, 'ส่ง follow-up ให้ครบอย่างน้อย 2 คน', 'metric', '2'),
    (3, 'มี meetup อย่างน้อย 1 ครั้ง', 'evidence', '1'),
    (4, 'เข้าร่วมกิจกรรมกลุ่มและมีส่วนร่วมชัดเจน 1 ครั้ง', 'manual', null),
    (5, 'ได้รับ feedback เชิงบวกเรื่องความน่าเชื่อถืออย่างน้อย 1 เคส', 'evidence', '1'),
    (6, 'แนะนำ connection ที่มีประโยชน์และเกิดการคุยต่อ', 'evidence', '1'),
    (7, 'เริ่ม collaboration กับคนในเครือข่ายอย่างน้อย 1 งาน', 'manual', null),
    (8, 'มีหลักฐานการนำวงคุย/ผลักดันการตัดสินใจอย่างน้อย 1 ครั้ง', 'evidence', '1'),
    (9, 'มีคนแนะนำ connection ใหม่ให้คุณโดยตรงอย่างน้อย 2 คน', 'metric', '2'),
    (10, 'รักษาวงคุณภาพสูงต่อเนื่อง 30 วัน พร้อมหลักฐานประกอบ', 'manual', '30_days')
  ) as t(level_id, requirement_text, requirement_type, required_value)
)
insert into public.social_requirements (level_id, requirement_text, requirement_type, required_value)
select level_id, requirement_text, requirement_type, required_value
from requirement_seed
where not exists (
  select 1
  from public.social_requirements sr
  where sr.level_id = requirement_seed.level_id
    and sr.requirement_text = requirement_seed.requirement_text
);

-- Keep Social score explicit at 0 until levels are passed.
insert into public.smv_dimension_scores (dimension_id, score, evidence_count_30d, guard_summary, explanation)
select id, 0, 0, 'Level progression 0/10', 'Social score มาจากด่านที่ผ่านเท่านั้น ด่านละ 10 คะแนน ไม่มี partial score'
from public.smv_dimensions
where key = 'social'
on conflict (dimension_id) do update
set
  score = excluded.score,
  guard_summary = excluded.guard_summary,
  explanation = excluded.explanation,
  updated_at = now();
